UPPER_THRESHOLD = 5.3
LOWER_THRESHOLD = -1.3
PERIOD = 10
STOP_LOSS = -277
TAKE_PROFIT = 495
TIME_OUT = 17  # in min
'''
USDT_START = 100000
OREDR_AMOUNT = 25000
BTC_AMOUNT = 0
ETH_AMOUNT = 0
PROFIT = USDT_START
PORTFOLIO_AFER_ORDER = USDT_START
BTC_AMOUNT_BEFOR_ORDER = BTC_AMOUNT
ETH_AMOUNT_BEFOR_ORDER = ETH_AMOUNT
LAST_ORDER = {
    'order' : None,
    'time' : None,
    'is_opened_position' : False,
    'btc_amount' : BTC_AMOUNT,
    'eth_amount' : ETH_AMOUNT
}
'''